source 'https://rubygems.org'
ruby '2.4.3'

gem 'acts-as-taggable-on', '~> 5.0'
gem "pundit"
gem 'ngrok-tunnel'
gem 'omniauth'
gem 'figaro'
gem 'jbuilder', '~> 2.0'
gem 'pg', '~> 0.21'
gem 'puma'
gem 'rails', '5.1.6'
gem 'redis'
gem 'devise'
gem 'autoprefixer-rails'
gem 'bootstrap-sass', '~> 3.3'
gem 'font-awesome-sass', '~> 4.7'
gem 'sass-rails'
gem 'simple_form'
gem 'uglifier'
gem 'webpacker'
gem 'omniauth-facebook'
gem 'simple_form_fancy_uploads'
gem 'acts_as_votable', '~> 0.11.1'
gem 'acts_as_favoritor'
gem 'cloudinary'
gem 'carrierwave', '~> 1.2'
gem 'faker'
gem 'social-share-button'
gem 'activeadmin', github: 'activeadmin/activeadmin'
gem 'inherited_resources', github: 'activeadmin/inherited_resources'
gem 'will_paginate', '~> 3.1.0'
gem 'stripe', :git => 'https://github.com/stripe/stripe-ruby'
gem 'stripe_event'

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'letter_opener'
end

group :development, :test do
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
